logging:
  file: 
    name: codeDeployer
    path: /apps/OpsERA/logs/components/code-deployer
server:
  port: 8077
  shutdown: graceful
   
spring:
  application:
    name: code-deployer
    description: API for integrating with deploy the code
  lifecycle:
    timeout-per-shutdown-phase: 2h
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

pipeline:
  config:
    baseurl: ${opsera.config.baseurl}/api/pipeline
aws:
  service:
    baseurl: ${opsera.config.baseurl}/api/aws
vault:
  service:
    baseurl: ${opsera.config.baseurl}/api/vault
jenkins:
  integrator:
    baseurl: ${opsera.config.baseurl}/api/jenkins

---

spring:
  profiles: kubernetes
opsera:
  config:
    baseurl: ${OPSERA_API_SERVICE_URL:http://opsera-apigateway.microservices.svc.cluster.local:9091}

