logging:
  file: 
    name: codeDeployer
    path: /apps/OpsERA/logs/components/code-deployer
server:
  port: 8077
  shutdown: graceful
   
spring:
  application:
    name: code-deployer
    description: API for integrating with deploy the code
  lifecycle:
    timeout-per-shutdown-phase: 2h

---

spring:
  profiles: kubernetes
pipeline:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/pipeline
aws:
  service:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/aws
vault:
  service:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/vault
jenkins:
  integrator:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/jenkins