logging:
   file: codeDeployer
   path: /apps/OpsERA/logs/components/code-deployer
server:
   port: 8077
   
spring:
 application:
    name: code-deployer
    description: API for integrating with deploy the code

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

---

spring:
 profiles: dev

pipeline:
 config:
  baseurl: http://microservices-dev.opsera.io:9091/api/pipeline
aws:
 service:
  baseurl: http://microservices-dev.opsera.io:9091/api/aws
vault:
 service:
  baseurl: http://microservices-dev.opsera.io:9091/api/vault
jenkins:
 integrator:
  baseurl: http://microservices-dev.opsera.io:9091/api/jenkins
eureka:
  client:
    serviceUrl:
      defaultZone: http://microservices-dev.opsera.io:8761/eureka/

---

spring:
 profiles: test
 
pipeline:
 config:
  baseurl: http://10.0.3.253:9091/api/pipeline
aws:
 service:
  baseurl: http://10.0.3.253:9091/api/aws
vault:
 service:
  baseurl: http://10.0.3.253:9091/api/vault
jenkins:
 integrator:
  baseurl: http://10.0.3.253:9091/api/jenkins
eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.0.3.253:8761/eureka/

---

spring:
 profiles: prod

pipeline:
 config:
  baseurl: http://10.0.2.4:9091/api/pipeline
aws:
 service:
  baseurl: http://10.0.2.4:9091/api/aws
vault:
 service:
  baseurl: http://10.0.2.4:9091/api/vault
jenkins:
 integrator:
  baseurl: http://10.0.2.4:9091/api/jenkins
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.4:9091/eureka/
      
---

spring:
 profiles: freetrial

pipeline:
 config:
  baseurl: http://10.0.2.164:9091/api/pipeline
aws:
 service:
  baseurl: http://10.0.2.164:9091/api/aws
vault:
 service:
  baseurl: http://10.0.2.164:9091/api/vault
jenkins:
 integrator:
  baseurl: http://10.0.2.164:9091/api/jenkins
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.164:9091/eureka/
      